version: '3.8'

services:
  fusionbrain-proxy:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO  # Измените на DEBUG для детального логирования
    volumes:
      # Опционально: монтируем сертификаты снаружи
      # - ./cert.pem:/app/cert.pem:ro
      # - ./key.pem:/app/key.pem:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 